export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INPUT_HANDLE = "INPUT_HANDLE";
export const BLUR_HANDLE = "BLUR_HANDLE";
export const FORM_VALIDATE = "FORM_VALIDATE";
export const RESET_VALID = "RESET_VALID";